version: '3.9'

services:
#  api:
#    build: .
#    container_name: api-express
#    ports:
#      - "3001:3000"
#    env_file:
#      - .env
#    depends_on:
#      - mongodb
#    environment:
#      - DOCKER=true
#    volumes:
#      - .:/usr/src/app


  mongodb:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 2326252
    volumes:
        - mongo_data:/data/db
volumes:
  mongo_data:

